### PR TITLE
Eslintconfig

### PR DESCRIPTION
**Pull request by Jarmister**
doesn't work .ts files

### CODE REVIEW

**Comment by Jarmister** [comment]
```
D:\4-WORK\Porekty hax\master\js-cashburn\cypress\plugins\index.js
  18:16  warning  Missing return type on function    @typescript-eslint/explicit-module-boundary-types
  18:17  warning  Argument 'on' should be typed      @typescript-eslint/explicit-module-boundary-types
  18:21  warning  Argument 'config' should be typed  @typescript-eslint/explicit-module-boundary-types

D:\4-WORK\Porekty hax\master\js-cashburn\server\server.lib.ts
  12:22  error  Promise executor functions should not be async                no-async-promise-executor        
  31:5   error  Do not use "@ts-ignore" because it alters compilation errors  @typescript-eslint/ban-ts-comment

D:\4-WORK\Porekty hax\master\js-cashburn\src\App.tsx
  1:8  error  'React' was used before it was defined  no-use-before-define

D:\4-WORK\Porekty hax\master\js-cashburn\src\components\BalanceForm.tsx
   1:8  error    'React' was used before it was defined  no-use-before-define
  27:3  warning  Missing return type on function         @typescript-eslint/explicit-module-boundary-types

D:\4-WORK\Porekty hax\master\js-cashburn\src\components\BalanceService.ts
  14:3  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types
  21:3  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

D:\4-WORK\Porekty hax\master\js-cashburn\src\components\ChartFunctional.js
   1:8   error    'React' was used before it was defined       no-use-before-define
   5:16  warning  Missing return type on function              @typescript-eslint/explicit-module-boundary-types
   5:17  warning  Object pattern argument should be typed      @typescript-eslint/explicit-module-boundary-types
   5:19  error    'values' is missing in props validation      react/prop-types
  11:33  error    'values.map' is missing in props validation  react/prop-types

D:\4-WORK\Porekty hax\master\js-cashburn\src\components\StatedBalanceForm.tsx
   1:8  error    'React' was used before it was defined  no-use-before-define
  14:3  warning  Missing return type on function         @typescript-eslint/explicit-module-boundary-types

D:\4-WORK\Porekty hax\master\js-cashburn\src\components\component_test\StatedBalanceForm.test.tsx
  3:8  error  'React' was used before it was defined  no-use-before-define

D:\4-WORK\Porekty hax\master\js-cashburn\src\components\navigator.js
  2:8   warning  Missing return type on function          @typescript-eslint/explicit-module-boundary-types
  2:23  warning  Object pattern argument should be typed  @typescript-eslint/explicit-module-boundary-types
  3:2   error    'navigation' is not defined              no-undef

D:\4-WORK\Porekty hax\master\js-cashburn\src\components\pages\Navigation.tsx
  1:8   error    'React' was used before it was defined  no-use-before-define
  4:20  warning  Missing return type on function         @typescript-eslint/explicit-module-boundary-types


D:\4-WORK\Porekty hax\master\js-cashburn\src\components\pages\StatedNameForm.tsx
  1:8   error    'React' was used before it was defined  no-use-before-define
  5:18  warning  Missing return type on function         @typescript-eslint/explicit-module-boundary-types

D:\4-WORK\Porekty hax\master\js-cashburn\src\main.tsx
  1:8  error  'React' was used before it was defined  no-use-before-define

D:\4-WORK\Porekty hax\master\js-cashburn\webpack.config.js
   1:14  error  Require statement not part of import statement  @typescript-eslint/no-var-requires
   2:27  error  Require statement not part of import statement  @typescript-eslint/no-var-requires
  36:12  error  'node_modules' is not defined                   no-undef

✖ 31 problems (17 errors, 14 warnings)
```

**Comment by oneacik** [comment]
I heard that @jawiemkto is trying to fix those errors.
Could you just write him to ask how he resolved some of them?

Maybe as he already used your branch it is not needed to merge with master.

**Comment by oneacik** [comment]
Btw. as you can see some checks are failing, check out the tests.
As I checked this is because you used node_modules as variable instead of "node_modules" literal 
(I'm not sure even if it is good usage).

**Review by jawiemkto — APPROVED** [review]
zmiany dotyczące konfiguracji eslinta i poprawki w kodzie pod niego wszystko spoko
pre-commit jeszcze na eslint zakomentowany, czeka aż cały projekt przejdzie sprawdzenie 
nie wiem czemu zmiana portu z 8080 na 8000 ale dla mnie to nie ma większego znaczenia

**Pull request merged**
